server:
  port: 9080

spring:
    profiles:
        # Available profiles: activeMQ|rabbitMQ|kafka
        active: rabbitMQ

generator:
    # Available category: ACS_RAW_EVENT|ACS_PUBLIC_EVENT|ACTIVITI_RAW_EVENT|ACTIVITI_PUBLIC_EVENT|CLOUD_CONNECTOR_EVENT
    eventCategory: CLOUD_CONNECTOR_EVENT
    startSendAtStartup: false
    # This property will be ignored if 'startSendAtStartup' is set to false
    shutdownAfterSend: true
    # This property will be ignored if 'shutdownAfterSend' is set to false
    waitBeforeShutdownInSeconds: 2
    scheduled:
        enabled: false
        # The period between successive executions in seconds
        periodInSeconds: 1
        # Number of events to send per second. Note: This is not guaranteed
        numOfEventsPerSecond: 1000
        # The duration of the task execution in seconds
        runForInSeconds: 10
    fixed:
        numOfEvents: 10
        pauseTimeInMillis: 1000

messaging:
    to:
        activemq:
            host: localhost
            port: 5672
            url: failover:(amqp://${messaging.to.activemq.host}:${messaging.to.activemq.port})?timeout=3000&startupMaxReconnectAttempts=0
            camelRoutes:
                - destinationName: alfresco.events.source
                  toRoute: amqpConnection:topic:${messaging.to.activemq.camelRoutes[0].destinationName}

        rabbitmq:
            host: localhost
            port: 5672
            username: guest
            password: guest
            virtualHost: "/"
            camelRoutes:
                - destinationName: acsCloudConnectorUpdateMetadata
                  toRoute: rabbitmq:${messaging.to.rabbitmq.camelRoutes[0].destinationName}?connectionFactory=#rabbitmqConnectionFactory&exchangeType=topic&autoDelete=false
                - destinationName: acsCloudConnectorMoveNode
                  toRoute: rabbitmq:${messaging.to.rabbitmq.camelRoutes[1].destinationName}?connectionFactory=#rabbitmqConnectionFactory&exchangeType=topic&autoDelete=false

        kafka:
            host: localhost
            port: 9092
            camelRoutes:
                - destinationName: alfresco.events.source
                  toRoute: kafka:${messaging.to.kafka.camelRoutes[0].destinationName}?brokers=${messaging.to.kafka.host}:${messaging.to.kafka.port}