server:
  port: 9090

spring:
    profiles:
        active: activeMQ

faker:
    numOfEvents: 10
    pauseTimeInMillis: 1000
    startSendAtStartup: true
    # This property will be ignored if 'startSendAtStartup' is set to false
    shutdownAfterSend: true
    # This property will be ignored if 'shutdownAfterSend' is set to false
    waitBeforeShutdownInMillis: 2000

messaging:
    to:
        activemq:
            host: localhost
            port: 5672
            url: failover:(amqp://${messaging.to.activemq.host}:${messaging.to.activemq.port})?timeout=3000&startupMaxReconnectAttempts=0
            camelRoute:
                destinationName: alfresco.faker.event.generator
                toRoute: amqp:topic:${messaging.to.activemq.camelRoute.destinationName}

        rabbitmq:
            host: localhost
            port: 5672
            username: guest
            password: guest
            virtualHost: "/"
            camelRoute:
                destinationName: alfresco.faker.event.generator
                toRoute: rabbitmq://${messaging.to.rabbitmq.host}:${messaging.to.rabbitmq.port}/${messaging.to.rabbitmq.camelRoute.destinationName}?connectionFactory=#rabbitmqConnectionFactory

        kafka:
            host: localhost
            port: 9092
            camelRoute:
                destinationName: alfresco.faker.event.generator
                toRoute: kafka:${messaging.to.kafka.camelRoute.destinationName}?brokers=${messaging.to.kafka.host}:${messaging.to.kafka.port}