server:
  port: 9080

spring:
    profiles:
        # Available profiles: activeMQ|rabbitMQ|kafka
        active: activeMQ

generator:
    # Available category: ACS_RAW_EVENT|ACS_PUBLIC_EVENT|ACTIVITI_RAW_EVENT|ACTIVITI_PUBLIC_EVENT|CLOUD_CONNECTOR_EVENT
    eventCategory: ACS_PUBLIC_EVENT
    startSendAtStartup: true
    # This property will be ignored if 'startSendAtStartup' is set to false
    shutdownAfterSend: true
    # This property will be ignored if 'shutdownAfterSend' is set to false
    waitBeforeShutdownInSeconds: 2
    scheduled:
        enabled: false
        # The period between successive executions in seconds
        periodInSeconds: 1
        # Number of events to send per second. Note: This is not guaranteed
        numOfEventsPerSecond: 1000
        # The duration of the task execution in seconds
        runForInSeconds: 10
    fixed:
        numOfEvents: 10
        pauseTimeInMillis: 1000

messaging:
    to:
        activemq:
            host: localhost
            port: 5672
            url: failover:(amqp://${messaging.to.activemq.host}:${messaging.to.activemq.port})?timeout=3000&startupMaxReconnectAttempts=0
            camelRoute:
                destinationName: alfresco.events.source
                toRoute: amqpConnection:topic:${messaging.to.activemq.camelRoute.destinationName}

        rabbitmq:
            host: localhost
            port: 5672
            username: guest
            password: guest
            virtualHost: "/"
            camelRoute:
                destinationName: engineEvents
                toRoute: rabbitmq:${messaging.to.rabbitmq.camelRoute.destinationName}?connectionFactory=#rabbitmqConnectionFactory&exchangeType=topic&autoDelete=false

        kafka:
            host: localhost
            port: 9092
            camelRoute:
                destinationName: alfresco.events.source
                toRoute: kafka:${messaging.to.kafka.camelRoute.destinationName}?brokers=${messaging.to.kafka.host}:${messaging.to.kafka.port}